version: '3'

services:
  postgresql-docker:
    image: postgres
    container_name: postgres-docker
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgresspassword
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - express-postgres-network
    restart: on-failure
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - postgresql-docker
    networks:
      - express-postgres-network
    ports:
      - "3333:3333"
    restart: always

volumes:
  postgresdata:
networks:
  express-postgres-network: